"""
Django settings for app_backend project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# -------------- Location of django application, current path
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# -------------- Unique of each project, do not make public
SECRET_KEY = '2&o^!b!=mmhgwkuxa2mkzcj-7ljt**#b+pba7zp+u56b$ot6c$'

# SECURITY WARNING: don't run with debug turned on in production!
# -------------- Useful for learning and developing, must be false in production
DEBUG = True

# -------------- Domain names allowed
ALLOWED_HOSTS = []


# Application definition
# -------------- Base of Django, small components of django server (products, prices, transacitons,...)
# -------------- Serve as the components of the project
INSTALLED_APPS = [
    'django.contrib.admin', # Go to 127.0.0.1:8000/admin -> 
    'django.contrib.auth', # User and super user auth to acess admin
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ----- Thidrd Party
    'rest_framework',
    'requests',
    'corsheaders',

    # ----- Own
    'helloworld',
    'energy'
]

# -------------- How request and security are handled
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = [
    'http://localhost:3000',
] # If this is used, then not need to use `CORS_ORIGIN_ALLOW_ALL = True`
CORS_ORIGIN_REGEX_WHITELIST = [
    'http://localhost:3000',
]

# -------------- How to route any given URL
ROOT_URLCONF = 'appdjango.urls'

# -------------- How to render HTML django templates, html pages rendered
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# -------------- How server works, settings of server
WSGI_APPLICATION = 'appdjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
# -------------- Database connection configuration
# -------------- using 'python3 manage.py migrate' create a database for sqlite (not yavailabre for another DB)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
# -------------- Default password validators, passwords are good enough
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/
# -------------- Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
# -------------- WHere static files (css, javascript, css)
STATIC_URL = '/static/'
