# Generated by Django 3.2 on 2021-04-14 00:24

from django.db import migrations, models
import energy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy_generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField()),
                ('tilt', models.FloatField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('energy', models.JSONField(default=energy.models.Energy_generation.energy_default, verbose_name='Energy')),
                ('average_energy', models.FloatField()),
                ('year', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Energy',
                'ordering': ['created_date'],
            },
        ),
    ]
